package pl.softwaremill.solver;

import org.drools.solver.core.score.calculator.HardAndSoftConstraintScoreCalculator;
import org.drools.solver.core.score.constraint.IntConstraintOccurrence;
import org.drools.solver.core.score.constraint.ConstraintType;

import pl.softwaremill.solver.domain.Assigment;
import pl.softwaremill.solver.domain.Preference;

// @author Adam Warski (adam at warski dot org)
// @author Geoffrey De Smet

global HardAndSoftConstraintScoreCalculator scoreCalculator;

// ############################################################################
// Hard constraints
// ############################################################################

rule "multipleAssigmentsPerSlot"
    when
        $assigment : Assigment($id : id, $slot : slot);
        exists Assigment(id > $id, slot == $slot);
    then
        insertLogical(new IntConstraintOccurrence("multipleAssigmentsPerSlot", ConstraintType.NEGATIVE_HARD, 1, $assigment));
end

// ############################################################################
// Soft constraints
// ############################################################################

rule "preferenceViolated"
    when
        $pref : Preference($paper1 : paper1, $paper2 : paper2, $weight: weight);
        Assigment(paper == $paper1, $slot1 : slot);
        Assigment(paper == $paper2, $slot2 : slot);
        eval($slot1.getTime() == $slot2.getTime());
    then
        insertLogical(new IntConstraintOccurrence("preferenceViolated", ConstraintType.NEGATIVE_SOFT, $weight, $pref));
end

// ############################################################################
// Calculate score
// ############################################################################

// Accumulate hard constraints
rule "hardConstraintsBroken"
        salience -1 // Do the other rules first (optional, for performance)
    when
        $hardTotal : Number() from accumulate(
            IntConstraintOccurrence(constraintType == ConstraintType.NEGATIVE_HARD, $weight : weight),
            sum($weight) // Vote for http://jira.jboss.com/jira/browse/JBRULES-1075
        );
    then
        scoreCalculator.setHardConstraintsBroken($hardTotal.intValue());
end

// Accumulate soft constraints
rule "softConstraintsBroken"
        salience -1 // Do the other rules first (optional, for performance)
    when
        $softTotal : Number() from accumulate(
            IntConstraintOccurrence(constraintType == ConstraintType.NEGATIVE_SOFT, $weight : weight),
            sum($weight) // Vote for http://jira.jboss.com/jira/browse/JBRULES-1075
        );
    then
        scoreCalculator.setSoftConstraintsBroken($softTotal.intValue());
end

